version: '3'

services:
  web:
    image: example/example-image:tag
    container_name: example_container_name
    restart: always
    ports:
      - '9990:80'
    privileged: true
  # api:
  #   image: ginlink/test-rollback:dev
  #   container_name: api
  #   restart: always
  #   ports:
  #     - '9010:9991'
  #   privileged: true

networks:
  lend_default:
    driver: bridge
