# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: work_rollback

on: workflow_dispatch

# on:
#   push:
#     tags:
#       - 'v*.*.*'

env:
  DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
  DOCKER_ACCESS_NAME: ${{ secrets.DOCKER_ACCESS_NAME }}
  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
  REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
  REMOTE_NAME: ${{ secrets.REMOTE_NAME }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: rollback
        run: ./sh/04action_rollback_local.sh
